apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ay-eks-cluster
  region: ap-south-1

nodeGroups:
   - name: nodegroup1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: aws-eks
   - name: nodegroup2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: aws-eks
